// Real browser drives the actual read-only endpoint, no mocked responses.
const fs=require('node:fs'),assert=require('node:assert/strict');const input=JSON.parse(fs.readFileSync(0,'utf8'));const {chromium}=require(input.playwright);
(async()=>{const browser=await chromium.launch({executablePath:input.browser,headless:true,args:['--disable-background-networking','--disable-component-update','--disable-sync','--no-first-run']});let checks=0;
if(input.correctionOnly){try{for(const language of ['en','zh-TW'])for(const width of [375,1024,1440]){
 const context=await browser.newContext({viewport:{width,height:1000}});await context.route('**/*',r=>r.request().url().startsWith(input.origin+'/')?r.continue():r.abort());const page=await context.newPage();await page.goto(input.origin+'/#/feed');await page.locator('.event-card').first().waitFor();for(const d of await page.locator('.event-intelligence-detail').all())await d.locator(':scope > summary').click();await page.locator('[data-language="'+language+'"]').click();
 const view=await page.evaluate(async()=>await(await fetch('/api/app/radar')).json());assert.equal(view.events.length,3);assert.ok(view.events.every(e=>e.event_geography.status==='UNKNOWN'&&e.verification_status==='UNVERIFIED_NEWS'));
 const europe=view.events.find(e=>e.context_geography.region_id==='europe'),global=view.events.find(e=>e.context_geography.region_id==='global'),multi=view.events.find(e=>e.context_geography.status==='MULTI_REGION');assert.ok(europe&&global&&multi);assert.equal(global.context_geography.centroid_lat,null);assert.equal(multi.context_geography.centroid_lat,null);
 const map=page.locator('.world-map');assert.equal(await map.locator('.institution-marker').count(),2);assert.equal(await map.locator('.context-marker').count(),1);assert.equal(await map.locator('[data-verified-count]').innerText(),'0');
 const anchor=map.locator('.context-marker');assert.equal(await anchor.getAttribute('data-marker-reference'),language==='en'?'Europe':'歐洲');assert.match(await page.locator('.event-card[data-event-id="'+global.event_id+'"] .context-intelligence>strong').first().innerText(),language==='en'?/Global/:/全球/);assert.match(await page.locator('.event-card[data-event-id="'+multi.event_id+'"] .context-intelligence>strong').first().innerText(),language==='en'?/Multiple supported regions/:/多個支持區域/);
 await anchor.focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.event-card:focus').getAttribute('data-event-id'),europe.event_id);assert.equal(await page.locator('.event-card:focus .event-geography').getAttribute('data-geography-status'),'UNKNOWN');
 for(const kind of ['context','institution','verified','all']){await map.locator('[data-map-filter="'+kind+'"]').click();assert.equal(await map.locator('[data-map-filter="'+kind+'"]').getAttribute('aria-pressed'),'true');assert.equal(await map.locator('[data-marker-kind]').count(),kind==='context'?1:kind==='institution'?2:kind==='verified'?0:3);}
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await context.close();checks++;
}}finally{await browser.close()}console.log(JSON.stringify({correction_fixture:'TEMP synthetic via actual API',groups:checks,all_pass:true,global_unpinned:true,multi_region_unpinned:true,europe_not_headquarters:true,network:'loopback only'}));return;}
try{for(const locale of ['en-US','zh-TW'])for(const width of [375,430,1024,1366,1440]){
 const context=await browser.newContext({locale,viewport:{width,height:1000}});await context.route('**/*',route=>route.request().url().startsWith(input.origin+'/')?route.continue():route.abort());const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto(input.origin+'/#/feed');try{await page.locator('.event-card').first().waitFor({timeout:5000})}catch(e){console.error('PAGE_ERRORS',errors,'BODY',await page.locator('body').innerText());throw e}assert.equal(await page.locator('.official-record').count(),2);assert.equal(await page.locator('.event-card').count(),input.events);assert.equal(await page.locator('.reality-replay').count(),input.events);
 for(const language of ['en','zh-TW']){
  await page.locator('[data-language="'+language+'"]').click();
  const map=page.locator('.world-map');assert.equal(await map.locator('.map-basemap .map-land').count(),1);assert.equal(await map.locator('.map-legend').isVisible(),true);assert.equal(await map.locator('[data-verified-count]').innerText(),'0');assert.ok(await map.locator('.context-marker').count()>0);assert.equal(await map.locator('.institution-marker').count(),2);
  assert.equal(await map.locator('[data-map-filter="verified"]').innerText(),language==='en'?'Source-supported Locations':'來源支持的事件位置');
  assert.match(await page.locator('.event-card[data-event-id="'+input.europeId+'"] .context-intelligence>strong').first().innerText(),language==='en'?/Europe$/:/歐洲$/);
  assert.match(await page.locator('.event-card[data-event-id="'+input.globalId+'"] .context-intelligence>strong').first().innerText(),language==='en'?/Global$/:/全球$/);
  assert.equal(await map.locator('.context-marker[data-marker-reference="'+(language==='en'?'Europe':'歐洲')+'"]').count(),1);assert.equal(await map.locator('.context-marker[data-marker-reference="'+(language==='en'?'Global':'全球')+'"]').count(),0);
  const ecb=page.locator('.event-card[data-event-id="'+input.ecbId+'"]');assert.match(await ecb.locator('.context-intelligence').innerText(),/European Central Bank/);assert.match(await ecb.locator('.context-intelligence').innerText(),/歐洲中央銀行/);assert.match(await ecb.locator('.context-intelligence').innerText(),language==='en'?/Frankfurt, Germany/:/德國法蘭克福/);assert.equal(await ecb.locator('.event-geography').getAttribute('data-geography-status'),'UNKNOWN');assert.match(await ecb.locator('.context-explanation').innerText(),language==='en'?/not an interest-rate decision/:/不是升息或降息決議/);
  for(const kind of ['verified','context','institution','all']){await map.locator('[data-map-filter="'+kind+'"]').focus();await page.keyboard.press('Enter');await page.waitForTimeout(20);assert.equal(await map.locator('[data-map-filter="'+kind+'"]').getAttribute('aria-pressed'),'true');const kinds=await map.locator('[data-marker-kind]').evaluateAll(nodes=>nodes.map(n=>n.dataset.markerKind));if(kind==='verified')assert.equal(kinds.length,0);else if(kind!=='all')assert.ok(kinds.length>0&&kinds.every(k=>k===kind));}
  const marker=map.locator('.institution-marker').first();await marker.focus();await page.keyboard.press('Enter');assert.equal(await map.locator('.map-location-list').isVisible(),true);await map.locator('.map-location-list [data-map-event]').first().click();assert.equal(await page.locator('.event-card:focus').count(),1);
const panel=page.locator('.event-card[data-event-id="'+input.eventId+'"]').locator('.reality-replay');if(!await panel.evaluate(e=>e.open)){await panel.locator('summary').focus();await page.keyboard.press('Enter')}
  assert.match(await panel.innerText(),language==='en'?/at or before the selected time/:/指定時間以前/);const field=panel.locator('input');assert.equal(await panel.locator('label').getAttribute('for'),await field.getAttribute('id'));
  await field.fill(input.before);await panel.locator('button').focus();await page.keyboard.press('Enter');await panel.locator('.replay-result').getByText(language==='en'?'No event observations existed in the ledger at this time.':'此時 ledger 尚無該事件觀測。',{exact:true}).waitFor();
  await panel.locator('input').fill(input.asOf);await panel.locator('button').click();await panel.locator('.replay-result .state-code').waitFor();const result=await panel.locator('.replay-result').innerText();assert.match(result,/AVAILABLE/);assert.match(result,language==='en'?/Observed by system/:/系統觀測時間/);assert.match(result,language==='en'?/Partial proposition-level official evidence/:/部分命題具有官方證據/);assert.match(result,language==='en'?/No linked market expectation/:/尚無已連結市場預期/);
  assert.equal(await panel.locator('.replay-result img').count(),0);assert.equal(await page.evaluate(()=>window.BAD||false),false);assert.match(result,/<img src=x/);
  await panel.locator('input').fill('invalid');await panel.locator('button').click();await panel.locator('.replay-result').getByText(/INVALID_REPLAY_AS_OF/).waitFor();assert.equal(await page.locator('.official-record').count(),2);
  const bounds=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(bounds.scroll<=bounds.width+1,JSON.stringify(bounds));assert.equal(await panel.locator('.replay-result').getAttribute('aria-live'),'polite');checks++;
 }
 assert.deepEqual(errors,[]);if(input.screenshot&&locale==='en-US'&&width===1440){await page.locator('.world-map').screenshot({path:input.screenshot})}await context.close();
}}finally{await browser.close()}console.log(JSON.stringify({real_browser:'Edge Chromium',groups:checks,all_pass:true,network:'loopback only',keyboard:'PASS',escaping:'PASS',context_map:'PASS',filters:'PASS',institution_dedup:'PASS',headquarters_not_event:'PASS'}))})().catch(e=>{console.error(e);process.exit(1)});
