// Actual installed Chromium/Edge, actual loopback API and served frontend.
// All non-loopback browser requests are blocked. No synthetic market fixture.
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const input=JSON.parse(fs.readFileSync(0,'utf8'));const {chromium}=require(input.playwright);
(async()=>{const browser=await chromium.launch({executablePath:input.browser,headless:true,args:['--disable-background-networking','--disable-component-update','--disable-sync','--no-first-run']});const results=[],blocked=[];
try{for(const width of [1280,375])for(const language of ['en','zh-TW']){
 const context=await browser.newContext({viewport:{width,height:1000},locale:language==='en'?'en-US':'zh-TW'});
 await context.route('**/*',r=>{if(r.request().url().startsWith(input.origin+'/'))return r.continue();blocked.push(r.request().url());return r.abort()});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(input.origin+'/#/feed');await page.locator('.watch-card').first().waitFor();await page.locator('[data-language="'+language+'"]').click();
 const view=await page.evaluate(async()=>await(await fetch('/api/app/radar')).json());assert.equal(view.prediction_market_watch.market_count,20);assert.ok(view.prediction_market_watch.markets.every(m=>m.source_status==='SAVED_SNAPSHOT'||m.source_status==='STALE'));
 assert.equal(await page.locator('.watch-card').count(),20);assert.equal(await page.locator('.watch-question-summary').count(),language==='zh-TW'?20:0);assert.equal(await page.locator('.event-intelligence-detail[open]').count(),0);
 const map=page.locator('#world-map'),watch=page.locator('#prediction-market-watch');let positions=await page.evaluate(()=>({map:document.querySelector('#world-map').getBoundingClientRect().top+scrollY,watch:document.querySelector('#prediction-market-watch').getBoundingClientRect().top+scrollY}));assert.ok(positions.map<positions.watch);
 const evidenced=page.locator('.event-card.has-evidence').first();await evidenced.locator('.event-intelligence-detail > summary').click();assert.ok(await evidenced.locator('.source-intelligence').isVisible());assert.ok(await evidenced.locator('.official-record').isVisible());assert.match(await evidenced.innerText(),/OFFICIAL_CONFIRMED/);assert.equal(await evidenced.getAttribute('data-event-status'),'UNVERIFIED_NEWS');assert.match(await evidenced.locator('.official-record').innerText(),language==='en'?/Published: Unknown/:/發布時間: 未知/);
 assert.match(await evidenced.locator('.source-intelligence').innerText(),language==='en'?/Last successful source check\nUnknown/:/最近成功檢查來源\n未知/);
 assert.ok(await evidenced.locator('.event-timeline').isVisible());assert.equal(await evidenced.locator('.timeline-entry').count(),2);assert.equal(await evidenced.locator('.event-geography').getAttribute('data-geography-status'),'UNKNOWN');
 await evidenced.locator('.macroview-preview > summary').click();assert.match(await evidenced.locator('.macroview-preview').innerText(),/PREVIEW/);assert.match(await evidenced.locator('.macroview-preview').innerText(),language==='en'?/not a frozen historical knowledge state/:/不是已凍結的歷史知識/);
 assert.equal(await evidenced.locator('.expectation-panel').count(),0);assert.ok(await evidenced.locator('.no-linked-expectation').isVisible());
 await evidenced.locator('.reality-replay > summary').click();assert.match(await evidenced.locator('.reality-replay').innerText(),/NO_RECORDED_HISTORY/);await evidenced.locator('.replay-controls input').fill('2026-10-08T18:00:00Z');await evidenced.locator('[data-replay-request]').click();await evidenced.locator('.replay-result').getByText(/INTELLIGENCE_REPLAY_UNAVAILABLE/).waitFor();assert.ok(await evidenced.locator('.event-intelligence-detail').evaluate(d=>d.open));
 const first=page.locator('.watch-card[data-market-id="2589810"]');if(language==='zh-TW'){assert.match(await first.locator('h3').innerText(),/至少 50 個基點/);await first.locator('.watch-original-question > summary').click();assert.equal(await first.locator('.watch-original-question p').innerText(),view.prediction_market_watch.markets.find(m=>m.market_id==='2589810').question);assert.match(await first.locator('.watch-outcomes').innerText(),/是（Yes）/)}else assert.match(await first.locator('h3').innerText(),/50\+ bps/);
 assert.ok((await first.locator('a[href^="https://polymarket.com/"]').count())>0);assert.match(await first.locator('.watch-updated').innerText(),/2026-10-08/);
 await page.locator('[data-watch-category="ENERGY"]').click();assert.equal(await page.locator('.watch-card').count(),5);await page.locator('[data-watch-category="ALL"]').click();assert.equal(await page.locator('.watch-card').count(),20);
 // Existing marker navigation opens the same event detail, not a new app.
 await map.locator('.map-location-list').locator('..').locator('summary').click();const nav=map.locator('.map-location-list [data-map-event]').first();assert.ok(await nav.count());const eventId=await nav.getAttribute('data-map-event');await nav.click();const target=page.locator('.event-card[data-event-id="'+eventId+'"]');assert.ok(await target.locator('.event-intelligence-detail').evaluate(d=>d.open));assert.equal(await page.locator('.event-card:focus').getAttribute('data-event-id'),eventId);
 const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(overflow.scroll<=width+1,JSON.stringify(overflow));assert.deepEqual(errors,[]);
 if(input.screenshots){await target.screenshot({path:path.join(input.screenshots,'v3-detail-'+language+'-'+width+'.png')});await first.screenshot({path:path.join(input.screenshots,'v3-market-'+language+'-'+width+'.png')});}
 results.push({language,width,realSavedMarkets:20,reviewedChinese:language==='zh-TW'?20:0,officialPropositionOnly:true,preview:true,replayUnavailableHonest:true,unknownHealth:true,mapBeforeWatch:true,mapNavigation:true,filters:true,overflow:false,errors});await context.close();
}}finally{await browser.close()}console.log(JSON.stringify({pass:true,results,externalRequestsBlocked:[...new Set(blocked)],network:'loopback only',providerSnapshot:'saved, not live'}));})().catch(e=>{console.error(e);process.exitCode=1});
