// Actual installed Edge and served PUBLIC candidate. External browser requests blocked.
// Inputs are previously captured real public feeds and the current real Watch API.
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const input=JSON.parse(fs.readFileSync(0,'utf8'));const {chromium}=require(input.playwright);
(async()=>{const browser=await chromium.launch({executablePath:input.browser,headless:true,args:['--disable-background-networking','--disable-component-update','--disable-sync','--no-first-run']});const results=[],blocked=[];
try{for(const width of [1280,375])for(const language of ['en','zh-TW']){
 const context=await browser.newContext({viewport:{width,height:1000},locale:language==='en'?'en-US':'zh-TW'});
 await context.route('**/*',r=>{if(r.request().url().startsWith(input.origin+'/'))return r.continue();blocked.push(r.request().url());return r.abort()});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(input.origin+'/#/feed');await page.locator('.watch-card').first().waitFor();await page.locator('[data-language="'+language+'"]').click();
 const view=await page.evaluate(async()=>await(await fetch('/api/app/radar')).json());assert.equal(view.prediction_market_watch.market_count,20);assert.equal(await page.locator('.watch-card').count(),20);
 assert.equal(view.news_freshness.last_24h_article_count,input.recent24);assert.equal(view.news_freshness.last_48h_article_count,input.recent48);
 assert.equal(await page.locator('.watch-question-summary').count(),language==='zh-TW'?20:0);assert.equal(await page.locator('h3[data-translation-mode="VALIDATED_QUESTION_TEMPLATE"]').count(),language==='zh-TW'?3:0);
 const refs=await page.locator('.recent-news-entry').evaluateAll(nodes=>nodes.map(n=>n.dataset.articleReference));const times=refs.map(ref=>view.news_freshness.published_at[ref]).filter(Boolean);assert.deepEqual(times,[...times].sort().reverse());
 const old=page.locator('.recent-news-entry[data-news-recency="OLDER"]');assert.ok(await old.count()>0);assert.ok(await page.locator('.recent-news-entry[data-news-recency="UNKNOWN"]').count()>0);
 const sourceChecks=page.locator('#latest-developments .support-details');await sourceChecks.locator('summary').click();assert.match(await sourceChecks.innerText(),/Global Voices/);assert.ok((await sourceChecks.innerText()).includes(view.discovery_sources['Global Voices'].last_success_at));const credited=view.items.find(a=>view.news_freshness.attribution?.[a.article_reference]?.source==='Global Voices');assert.ok(credited);assert.ok((await page.locator('#latest-developments').innerText()).includes(view.news_freshness.attribution[credited.article_reference].author));assert.ok(await page.locator('a[href="https://creativecommons.org/licenses/by/3.0/"]').count()>0);
 await page.locator('[data-news-window="24H"]').click();assert.equal(await page.locator('.recent-news-entry').count(),input.recent24);assert.equal(await page.locator('.recent-news-entry[data-news-recency="OLDER"]').count(),0);
 await page.locator('[data-news-window="48H"]').click();assert.equal(await page.locator('.recent-news-entry').count(),input.recent48);await page.locator('[data-news-window="ALL"]').click();assert.equal(await page.locator('.recent-news-entry').count(),view.news_item_count);
 let positions=await page.evaluate(()=>({map:document.querySelector('#world-map').getBoundingClientRect().top+scrollY,watch:document.querySelector('#prediction-market-watch').getBoundingClientRect().top+scrollY}));assert.ok(positions.map<positions.watch);
 const evidenced=page.locator('.event-card.has-evidence').first();await evidenced.locator('.event-intelligence-detail > summary').click();assert.ok(await evidenced.locator('.source-intelligence').isVisible());assert.ok(await evidenced.locator('.official-record').isVisible());assert.match(await evidenced.innerText(),/OFFICIAL_CONFIRMED/);assert.equal(await evidenced.getAttribute('data-event-status'),'UNVERIFIED_NEWS');assert.match(await evidenced.locator('.official-record').innerText(),language==='en'?/Published: Unknown/:/發布時間: 未知/);
 await evidenced.locator('.macroview-preview > summary').click();assert.match(await evidenced.locator('.macroview-preview').innerText(),/PREVIEW/);await evidenced.locator('.reality-replay > summary').click();assert.match(await evidenced.locator('.reality-replay').innerText(),/NO_RECORDED_HISTORY/);
 const first=page.locator('.watch-card[data-market-id="3399459"]');if(language==='zh-TW'){assert.match(await first.locator('.watch-question-summary').innerText(),/以色列與伊朗.*持續到並涵蓋 10 月 31 日/);await first.locator('.watch-original-question > summary').click();assert.equal(await first.locator('.watch-original-question p').innerText(),'Israel x Iran ceasefire continues through October 31?');assert.match(await first.locator('.watch-outcomes').innerText(),/是（Yes）/)}else assert.match(await first.locator('h3').innerText(),/Israel x Iran/);
 // A separate future unknown proposition checks fallback; never counted as real data.
 const fallback=await page.evaluate(()=>window.RadarMarketTranslation.project({market_id:'unknown-fixture',question:'Will the Fed cut more than 75 bps before June?',category:'MONETARY_POLICY'},'zh-TW'));assert.equal(fallback.mode,'TERMINOLOGY_ONLY');assert.equal(fallback.summary,null);
 await page.locator('[data-watch-category="ENERGY"]').click();assert.equal(await page.locator('.watch-card').count(),5);await page.locator('[data-watch-category="ALL"]').click();
 const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(overflow.scroll<=width+1,JSON.stringify(overflow));assert.deepEqual(errors,[]);
 if(input.screenshots){await page.locator('#latest-developments').evaluate(e=>scrollTo(0,e.getBoundingClientRect().top+scrollY-12));await page.screenshot({path:path.join(input.screenshots,'v4-news-'+language+'-'+width+'.png')});await first.screenshot({path:path.join(input.screenshots,'v4-market-'+language+'-'+width+'.png')});}
 results.push({language,width,realNews:view.news_item_count,recent24:input.recent24,recent48:input.recent48,realCurrentMarkets:20,reviewedQuestions:17,validatedTemplates:3,originalAccessible:true,chronology:true,filters:true,unknownPublication:true,sourceChecks:true,officialPropositionOnly:true,preview:true,replayUnavailable:true,mapBeforeWatch:true,overflow:false,errors});await context.close();
}}finally{await browser.close()}console.log(JSON.stringify({pass:true,results,externalRequestsBlocked:[...new Set(blocked)],network:'loopback only; saved real current provider responses',syntheticItemsCounted:0}));})().catch(e=>{console.error(e);process.exitCode=1});
