// Installed real browser; server input is saved real provider responses, not invented stories.
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const i=JSON.parse(fs.readFileSync(0,'utf8')), {chromium}=require(i.playwright);
(async()=>{const b=await chromium.launch({executablePath:i.browser,headless:true,args:['--disable-background-networking','--disable-component-update','--disable-sync']});const results=[];
try{for(const width of [1280,375])for(const lang of ['en','zh-TW']){
 const c=await b.newContext({viewport:{width,height:1000},locale:lang==='en'?'en-US':'zh-TW'});
 await c.route('**/*',r=>r.request().url().startsWith(i.origin+'/')?r.continue():r.abort());const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));
 await p.goto(i.origin+'/#news-items');await p.locator('.recent-news-entry').first().waitFor();await p.locator('[data-language="'+lang+'"]').click();
 const v=await p.evaluate(async()=>await(await fetch('/api/app/radar')).json()),n=v.news_intelligence,f=v.news_freshness;
 assert.equal(v.news_item_count,i.news);assert.equal(await p.locator('.recent-news-entry').count(),i.news);assert.equal(await p.locator('.brief-entry').count(),n.brief_article_references.length);assert.ok(n.brief_article_references.length>0&&n.brief_article_references.length<=5);
 for(const ref of n.brief_article_references){const card=n.cards[ref];assert.ok(['LAST_24H','LAST_48H'].includes(card.recency));assert.ok(card.macro_relevant&&card.provenance_valid);assert.equal(card.novelty_status,'NOT_ESTABLISHED');const a=v.items.find(a=>a.article_reference===ref);assert.ok(a);const node=p.locator('.brief-entry').filter({has:p.locator('h3',{hasText:a.title})});assert.ok((await node.innerText()).includes(a.news_source.name));assert.ok(await node.locator('a').evaluateAll((links,u)=>links.some(l=>l.href===u),a.news_source.url));assert.match(await node.innerText(),/UNVERIFIED_NEWS/);assert.equal(a.event_occurred_at,null)}
 const refs=await p.locator('.recent-news-entry').evaluateAll(ns=>ns.map(n=>n.dataset.articleReference));assert.equal(new Set(refs).size,i.news);const times=refs.map(r=>f.published_at[r]).filter(Boolean);assert.deepEqual(times,[...times].sort().reverse());
 assert.equal(await p.locator('[data-related-event]').count(),n.related_coverage.length);assert.equal(n.related_coverage.length,0); // This REAL data has no proven multi-report rate-decision group.
 const insight=p.locator('.recent-news-entry .news-insight').first();assert.match(await insight.innerText(),lang==='zh-TW'?/為何值得查核/:/Why investigate/);assert.match(await insight.innerText(),lang==='zh-TW'?/非標題全文翻譯/:/not a headline translation/);
 assert.equal(await p.locator('.watch-card').count(),20);assert.ok(await p.locator('#world-map').count());assert.ok(await p.locator('#world-map [data-map-filter]').count());await p.locator('[data-map-filter="context"]').click();await p.locator('[data-map-filter="all"]').click();
 const positions=await p.evaluate(()=>({map:document.querySelector('#world-map').getBoundingClientRect().top+scrollY,watch:document.querySelector('#prediction-market-watch').getBoundingClientRect().top+scrollY}));assert.ok(positions.map<positions.watch);
 const button=p.locator('.brief-entry [data-map-event]').first(),eventId=await button.getAttribute('data-map-event');await button.click();assert.ok(await p.locator('#event-'+eventId+' .event-intelligence-detail').getAttribute('open')!==null);assert.ok(await p.locator('#event-'+eventId+' .context-intelligence').isVisible());
 const official=p.locator('.event-card.has-evidence').first();await official.locator('.event-intelligence-detail').evaluate(e=>e.open=true);assert.equal(await official.getAttribute('data-event-status'),'UNVERIFIED_NEWS');assert.match(await official.innerText(),/OFFICIAL_CONFIRMED/);await official.locator('.macroview-preview').evaluate(e=>e.open=true);assert.match(await official.innerText(),/PREVIEW/);await official.locator('.reality-replay').evaluate(e=>e.open=true);assert.match(await official.innerText(),/NO_RECORDED_HISTORY/);assert.equal(v.official_evidence.length,2);assert.ok(v.official_evidence.some(e=>e.published_at===null));
 await p.locator('[data-news-window="24H"]').click();assert.equal(await p.locator('.recent-news-entry').count(),f.last_24h_article_count);await p.locator('[data-news-window="48H"]').click();assert.equal(await p.locator('.recent-news-entry').count(),f.last_48h_article_count);await p.locator('[data-news-window="ALL"]').click();assert.equal(await p.locator('.recent-news-entry').count(),i.news);
 assert.ok(await p.locator('.recent-news-entry[data-news-recency="UNKNOWN"]').count());assert.ok(await p.locator('a[href="https://creativecommons.org/licenses/by/3.0/"]').count());
 await p.locator('#latest-developments .support-details').evaluate(e=>e.open=true);assert.match(await p.locator('#latest-developments').innerText(),/REQUEST_TIMEOUT/);assert.equal(v.discovery_sources['UN News'].enabled,false);assert.equal(v.discovery_sources['Guardian World'].enabled,false);assert.equal(v.health_status,'UNKNOWN');
 assert.equal(await p.locator('#news-items').evaluate(e=>e.tagName),'SECTION');const overflow=await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert.ok(overflow<=1,'overflow '+overflow);assert.deepEqual(errors,[]);
 await p.locator('#macro-brief').evaluate(e=>scrollTo(0,e.getBoundingClientRect().top+scrollY-12));await p.screenshot({path:path.join(i.screenshots,'v42-news-'+lang+'-'+width+'.png')});
 await p.locator('.brief-entry').first().screenshot({path:path.join(i.screenshots,'v42-card-'+lang+'-'+width+'.png')});
 results.push({width,language:lang,news:i.news,brief:n.brief_article_references.length,macro24:n.macro_relevant_last_24h,recent24:f.last_24h_article_count,recent48:f.last_48h_article_count,related:n.related_coverage.length,unknownAnalysis:n.unknown_analysis_count,filter:true,chronology:true,links:true,contextButton:true,officialPropositionOnly:true,mapBeforeWatch:true,watch20:true,timeoutCachePreserved:true,unknown:true,overflow:false,pageErrors:errors});await c.close();
 }}finally{await b.close()}console.log(JSON.stringify({pass:true,realBrowser:'Microsoft Edge',input:'saved real source-backed feed responses and saved real Watch',results,externalRequestsAllowed:false,syntheticNewsCount:0}));})().catch(e=>{console.error(e);process.exitCode=1});
